### ISSUE TITLE
Change under_score to camelCase on REST.

### ISSUE THREAD

**Issue by kyunooh** [triplepy/sh8email-django#11]
I think that is just taste. but I got a answer about that.

**Comment by kyunooh** [comment]
This is present for you. @kangsLee

**Comment by kyunooh** [comment]
I will check it later  https://github.com/vbabiy/djangorestframework-camel-case

**Comment by kangsLee** [comment]
Hey, Why you change your mind?

**Comment by kyunooh** [comment]
Yeah this would be merge next deploy.
