### ISSUE TITLE
Content of secret mail is revealed.

### ISSUE THREAD

**Issue by getogrand** [triplepy/sh8email-django#13]
Content of secret mail is revealed on list page.
![image](https://cloud.githubusercontent.com/assets/7913887/18515913/f486e524-7ad1-11e6-8749-f64c762cc34a.png)

**Comment by kyunooh** [comment]
That is side effect, sorry.

**Comment by kyunooh** [comment]
oops this is not side effect. why we don't cate about it? ....

**Comment by getogrand** [comment]
I'll try to solve this problem.

**Comment by getogrand** [comment]
Fixed on https://github.com/triplepy/sh8email-django/commit/5190c526e314c2b31fce5aa1fb214b299e5c37e8.
![image](https://cloud.githubusercontent.com/assets/7913887/18556055/21577680-7ba5-11e6-9d20-137744faadf2.png)
