### ISSUE TITLE
The character '#' appeared when you click check in button.

### ISSUE THREAD

**Issue by getogrand** [triplepy/sh8email-django#14]
The character '#' appeared when you click check in button.
![image](https://cloud.githubusercontent.com/assets/7913887/18516140/cb103c8a-7ad2-11e6-95ab-b30f1b5ba713.png)
![image](https://cloud.githubusercontent.com/assets/7913887/18516159/dd2ff324-7ad2-11e6-9da5-46ecbcf578e7.png)

**Comment by kyunooh** [comment]
Haha actually, I know about it.... Sorry I will fix it.

**Comment by kyunooh** [comment]
It would be resolved next deploy
