### ISSUE TITLE
Apply djangorestframework-camel-case.

### ISSUE THREAD

**Issue by getogrand** [triplepy/sh8email-django#16]
How about use [djangorestframework-camel-case](https://github.com/vbabiy/djangorestframework-camel-case) for making restapi result to camel case instead of using 'serializer field name and _source_ kwargs option'.
See #11 .

**Comment by kyunooh** [comment]
Actually I tried to use it yesterday. but **it have two issues.**
First, I don't know why result is crush on Safari. It seems like about **character encoding**.(It was fine on Chrome) 
Second, We can't use DRF default renderer when use it. It means we need another rest api client like postman. **drf-camel-case don't support test tool on browser**...
if our services was bigger and bigger. then we will think about it later. I think we don't need it yet :D.

**Comment by getogrand** [comment]
OK, then I'll close this issue!
