### ISSUE TITLE
merge settings file

### ISSUE THREAD

**Issue by kyunooh** [triplepy/sh8email-django#18]
Now, divided settings files(common_settings, settings)

**Comment by getogrand** [comment]
Why do you want merge these setting files?

**Comment by kyunooh** [comment]
I thought we talked about it enough, when last Saturday. when we added some setting property, we have to add twice now. it is about `import *` style

**Comment by getogrand** [comment]
OK I got it!

**Comment by kyunooh** [comment]
I made it! close issue.
