### ISSUE TITLE
Improve REST url design.

### ISSUE THREAD

**Issue by getogrand** [triplepy/sh8email-django#3]
@triplepy/server 
We should to discuss about designing REST url. I think that urls have to be changed to more RESTy.
Here is a my url suggestion below.

```
- View the list of emails: /rest/mail/
- View/edit an email: /rest/mail/{mail_pk}/
```

**Comment by kyunooh** [comment]
How about like this?

``` python
/rest/{nickname}/mail/{mail_pk}/ or /rest/mail/{nickname}/{mail_pk}/
```

If we did like that, we don't need check session.

**Comment by getogrand** [comment]
I think we cannot remove using session.
We are using session for determining whether user does recheckin or not.
Here is use case: Wonyoung accesses the mail detail page. Unfortunately, the phone misses Wifi so that wonyoung press refresh button of web browser.
In this case, if we don't have session, the mail would have gone to heaven, so Wonyoung might be upset.

**Comment by kyunooh** [comment]
Hahaha Okay, then we don't remove session.  but still I think that url with nickname is better. How about it?

**Comment by getogrand** [comment]
It makes sense. I prefer /rest/mail/{nickname}/{mail_pk}/.

**Comment by kyunooh** [comment]
Ok then I will try like that 👍

**Comment by kyunooh** [comment]
@kangsLee check this out!

**Comment by kyunooh** [comment]
It would be merged next deploy.
