### ISSUE TITLE
Divide mail receiver server and web server

### ISSUE THREAD

**Issue by kyunooh** [triplepy/sh8email-django#4]

**Comment by kyunooh** [comment]
We need to disconnect mail delete job with receiver server.

**Comment by getogrand** [comment]
I've found good stuff for this issue.
[We can write custom django-admin commands.](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/)

Using above, we may run delete-batch-server and mail-receiver-server with below commands.

``` shell
python manage.py runbatch
python manage.py runrecv
```

**Comment by kyunooh** [comment]
Thanks @getogrand. I'm glad to complete it!
